# Generated by Django 4.2.3 on 2023-07-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Shipping', 'verbose_name_plural': 'Shipping Address'},
        ),
    ]
