# Generated by Django 4.2.3 on 2023-07-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='images/'),
        ),
    ]
