# Generated by Django 4.2.3 on 2023-08-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ratingstar_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
