# Generated by Django 4.2.3 on 2023-07-28 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ratingstar_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.product'),
        ),
    ]
